[package]
name = "rusting_around"
version = "0.1.0"
authors = ["Ranovan7 <romyranovan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tsp = { path = "crates/tsp" }

[workspace]
members = ["crates/*"]
